name: infgety_database
description: Dart library for secure data, HTTP utilities, and contact management with Infgety database integration.
version: 1.0.0
repository: https://github.com/PSHTeam/infgety_database.git

environment:
  sdk: ^3.8.1

dependencies:
  encrypt: ^5.0.3
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
